// Package crypto provides cryptographic utilities for KNDIS
// including SPID generation, JWT signing, and DPoP validation
package crypto

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base32"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"golang.org/x/crypto/curve25519"
)

// Sector constants as defined in the blueprint
const (
	SectorHealth    = "KONOHA_HEALTH_V1"
	SectorTax       = "KONOHA_TAX_V1"
	SectorBanking   = "KONOHA_BANK_V1"
	SectorVoting    = "KONOHA_VOTE_V1"
	SectorEducation = "KONOHA_EDU_V1"
	SectorTelecom   = "KONOHA_TELECOM_V1"
	SectorTravel    = "KONOHA_TRAVEL_V1"
)

// Sector prefixes for SPIDs
var sectorPrefixes = map[string]string{
	SectorHealth:    "H-",
	SectorTax:       "T-",
	SectorBanking:   "B-",
	SectorVoting:    "V-",
	SectorEducation: "E-",
	SectorTelecom:   "K-",
	SectorTravel:    "P-",
}

// SPIDGenerator handles SPID derivation using HMAC-SHA256
// In production, this would interface with an HSM
type SPIDGenerator struct {
	sectorKeys map[string][]byte // sector -> HMAC key
}

// NewSPIDGenerator creates a new SPID generator with sector keys
func NewSPIDGenerator(keys map[string][]byte) *SPIDGenerator {
	return &SPIDGenerator{
		sectorKeys: keys,
	}
}

// GenerateNIN creates a new National Identity Number (UUID v4)
// In production, this would be generated by the CIV and stored in HSM
func GenerateNIN() string {
	return uuid.New().String()
}

// GenerateSPID derives a Sector Pseudonymous ID from a NIN
// SPID = HMAC-SHA256(NIN || sector_constant) truncated to 128 bits
func (g *SPIDGenerator) GenerateSPID(nin string, sector string) (string, error) {
	key, ok := g.sectorKeys[sector]
	if !ok {
		return "", fmt.Errorf("unknown sector: %s", sector)
	}

	prefix, ok := sectorPrefixes[sector]
	if !ok {
		return "", fmt.Errorf("no prefix for sector: %s", sector)
	}

	// HMAC-SHA256(NIN || sector)
	data := nin + sector
	h := hmac.New(sha256.New, key)
	h.Write([]byte(data))
	sum := h.Sum(nil)

	// Truncate to 128 bits (16 bytes) and encode as Base32
	// 16 bytes = 128 bits = 26 characters in Base32
	truncated := sum[:16]
	encoded := base32.StdEncoding.EncodeToString(truncated)

	// Format: PREFIX-XXXXXXXXXXXXXXXXXXXXXXXXXX
	return prefix + encoded, nil
}

// ValidateSPID checks if an SPID has the correct format for its sector
func ValidateSPID(spid string, sector string) bool {
	prefix, ok := sectorPrefixes[sector]
	if !ok {
		return false
	}

	if !strings.HasPrefix(spid, prefix) {
		return false
	}

	// Check length: prefix (2) + dash (1) + 26 chars = 29
	if len(spid) != 29 {
		return false
	}

	return true
}

// ExtractSectorFromSPID determines the sector from an SPID prefix
func ExtractSectorFromSPID(spid string) (string, error) {
	if len(spid) < 3 {
		return "", fmt.Errorf("invalid SPID format")
	}

	prefix := spid[:2]
	for sector, p := range sectorPrefixes {
		if p == prefix+"-" {
			return sector, nil
		}
	}

	return "", fmt.Errorf("unknown SPID prefix: %s", prefix)
}

// DPoPProof represents a DPoP proof JWT structure
type DPoPProof struct {
	Header    DPoPHeader    `json:"header"`
	Payload   DPoPPayload   `json:"payload"`
	Signature string        `json:"signature"`
}

// DPoPHeader contains the DPoP JWT header
type DPoPHeader struct {
	Alg string                 `json:"alg"`
	Typ string                 `json:"typ"`
	JWK map[string]interface{} `json:"jwk"`
}

// DPoPPayload contains the DPoP JWT payload
type DPoPPayload struct {
	JTI string `json:"jti"`           // Unique token ID
	HTM string `json:"htm"`           // HTTP method
	HTU string `json:"htu"`           // HTTP URL
	IAT int64  `json:"iat"`           // Issued at
	ATH string `json:"ath,omitempty"` // Access token hash (for binding)
}

// ValidateDPoP validates a DPoP proof against the request
func ValidateDPoP(proof string, method string, url string, accessToken string) error {
	// Parse the DPoP proof JWT
	parts := strings.Split(proof, ".")
	if len(parts) != 3 {
		return fmt.Errorf("invalid DPoP proof format")
	}

	// Decode payload
	payloadBytes, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return fmt.Errorf("failed to decode DPoP payload: %w", err)
	}

	var dpop DPoPPayload
	if err := json.Unmarshal(payloadBytes, &dpop); err != nil {
		return fmt.Errorf("failed to unmarshal DPoP payload: %w", err)
	}

	// Validate HTTP method
	if dpop.HTM != method {
		return fmt.Errorf("DPoP method mismatch: expected %s, got %s", method, dpop.HTM)
	}

	// Validate HTTP URL
	if dpop.HTU != url {
		return fmt.Errorf("DPoP URL mismatch: expected %s, got %s", url, dpop.HTU)
	}

	// Validate access token hash if present
	if accessToken != "" && dpop.ATH != "" {
		hash := sha256.Sum256([]byte(accessToken))
		expectedATH := base64.RawURLEncoding.EncodeToString(hash[:])
		if dpop.ATH != expectedATH {
			return fmt.Errorf("DPoP access token hash mismatch")
		}
	}

	return nil
}

// GenerateDPoPThumbprint generates a JWK thumbprint for DPoP binding
func GenerateDPoPThumbprint(publicKey []byte) string {
	// Simplified thumbprint - in production, use proper JWK thumbprint
	hash := sha256.Sum256(publicKey)
	return base64.RawURLEncoding.EncodeToString(hash[:])
}

// GenerateX25519KeyPair generates an X25519 key pair for DPoP
func GenerateX25519KeyPair() (privateKey, publicKey []byte, err error) {
	privateKey = make([]byte, curve25519.ScalarSize)
	// In production, use crypto/rand for secure random
	// This is a simplified version
	for i := range privateKey {
		privateKey[i] = byte(i)
	}

	publicKey, err = curve25519.X25519(privateKey, curve25519.Basepoint)
	if err != nil {
		return nil, nil, err
	}

	return privateKey, publicKey, nil
}